{%
	// Helper functions
	function get_radio_list() {
		let radios = [];

		for (let phy in fs.glob('/sys/class/ieee80211/*'))
			push(radios, fs.basename(phy));

		return radios;
	}

	// Configuration generation functions
	function generate_umap_agent(netdev, no_ubus) {
		let output = [];
		let radios = get_radio_list();

		uci_comment(output, '# generated by easymesh-agent.uc');
		uci_comment(output, '### generate umap agent');
		uci_section(output, 'umapd agent');
		uci_set_number(output, 'umapd.@agent[-1].verbosity', 1);
		uci_list_string(output, 'umapd.@agent[-1].bridge', netdev);
		uci_list_string(output, 'umapd.@agent[-1].no_ubus', no_ubus ? '1' : '0');

		for (let radio in radios)
			uci_list_string(output, 'umapd.@agent[-1].radio', radio);

		return uci_output(output);
	}
%}
{{ generate_umap_agent(netdev, no_ubus) }}

